name: Prticl
version: '1.0.0'
main: com.minkuh.prticl.Prticl
api-version: '1.21'
authors: [ Minkuh ]
commands:
  prticl:
    description: The PRTICL command
    usage: /<command> [sub-command] (params)