name: Prticl
version: '${project.version}'
main: com.minkuh.prticl.Prticl
api-version: '1.20'
commands:
  hi:
    description: Says hi back to you!
    aliases:
      - hello
      - greetings
    usage: /<command> (message)
  prticl:
    description: The PRTICL command
    usage: /<command> [sub-command] (params)
